spring:
    datasource:
      url: jdbc:mysql://localhost:3306/gas?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            format_sql: true